### ISSUE TITLE
Thank you for sharing your journey and great career tips! 

### ISSUE THREAD

**Issue by linesbetween** [Lucie-Wang/ama#1]
Hi Lucie and other friends who attended the lecture, nice to meet you all. 
This PR is not for an answer, but more for emotional expression. Hope it's not too off-topic.
Honing skills and looking for a job at the same time is stressful. During this time, a little human support may bring out our full potential. Glad Lucie opened this space for us. 

May we enjoy the journey together.

**Comment by Lucie-Wang** [comment]
Thanks for your message! I am glad that you enjoyed the session today and hope it is helpful. Please let me know if you have any questions in the future:)
一起加油！
