### ISSUE TITLE
感谢你在来offer的分享，有个问题想咨询一下你

### ISSUE THREAD

**Issue by chu017** [Lucie-Wang/ama#2]
Lucie，你好，

我是学建筑设计的，毕业后在旧金山工作3年多了。最近决定全职转码农。听你介绍你有在美国bootcamp和来offer学习的双重经历。我有个疑问是关于对比美国Boot Camp和来off学习，对于在疫情环境下找到工作，哪个帮助更大。

我现在在上一个美国的bootcamp (Hact Reactor) 。这是是3个月的JavaScript full stack development immersive课程。我是经朋友介绍。他是通过这个Boot Camp的学习就直接找到了码农的工作。在我学习一段时间后，也是发现了这个Boot Camp主要是带学生做前端和后段的项目，对算法和系统设计的知识教授的比较少。

面对现在由于疫情而变得困难的就业环境，我不知道，是否在这个Boot Camp结束以后可以顺利的找到码农的工作。还是之后又要通过自己去大量的刷题，或再去上来offer课程来帮助找到工作。与其如此，不如直接停了这个课程，去上来offer的课。

我想问问你的意见，你觉得Boot Camp的经历对你找工作的帮助大吗，我有必要把这个Boot Camp上完吗？还是在来offer学习的经历和自己刷题与面试准备的作用会更大一些。（我并不一定要去大公司工作，我还挺想去小的startup 工作）。

感谢！

Calvin

**Comment by linesbetween** [comment]
Lucie姐来之前我先抢答一下， 刚好认识了一些code bootcamp的人和老师，普遍的说法是找工作不易，上完课程还要接着自己找项目做，工作很多也是小公司，兼职，这还是美国人。有人说毕业后平均6个月找到工作。
Lucie姐提到的Apprentice项目是进入大公司的好途径。
Lai Offer没上过，看课程大纲很硬核，求职也是以大公司为主。借地问一下Lucie, Lai Offer有内推吗？机会多吗？

**Comment by Lucie-Wang** [comment]
@chu017 谢谢你的问题。我听说过你提到的这个Boot Camp，感觉网上的评价其实还不错。我个人是觉得bootcamp出来，尤其是去年其实就业率不是很理想。我去年同期的和附近几期的只有屈指可数的几个人找到工作，很多找到工作的也只是icc或者很小的公司。工作面试的话，无论大公司还是小公司都是要做算法题的，如果你面前端会有一些take home assignments，算法是怎么都需要攻克的。我认为bootcamp有这么几个优势：
1. 有一些校友，就业的资源可以利用，比如我的bootcamp跟一个大公司还有合作，我也用过career services的一些信息和帮助；
2. 有一定的知名度，比如有些学徒项目直接就是说bootcamp毕业6个月之后才能申请等等；
3. 还是能够学到一些编程的知识，尤其是你学的这个算是比较深入的js的课程，要比我之前14周3个fullstack要更系统一些。

你现在如果只会javascript还是有一些缺憾：
1. javascript总的来说还是一个偏前端的语言，而前端更多用react这类的library，你是不是有很好的掌握？
2. 算法用javascript来写的话一般属于programming language的鄙视链最底层，其实没什么，但是一般大部分岗位特别是偏后端的岗位都用的java，差别很大。我学了java以后，后来想提前学一点微软的c#，完全没有障碍，因为相似度很大，我写python的朋友就非常吃力。我还有个朋友面试用的python，进了新工作要写java，也非常头疼因为不太会又没有地方可以系统学。多会一些语言，并且掌握好oop的语言，在以后的工作中是非常实用的。
3. bootcamp对算法的要求不严，现在市场艰难的时候是非常没有竞争力的。你还是要去做题，练习，分析，即使不上来offer，udemy的课，其他的课也得跟上，不然你后面一个人刷体会很痛苦。
大公司的机会多，startup招人门槛也不低的，去年我看过来，startup不愿意找新人，都要多年工作经验的，所以不要想着公司小标准就低，而是要想着把自己的实力提升到越高越好。

我不是很清楚你目前上到什么程度，如果中途退出对你的financial会不会有影响。我个人是bootcamp还没有结束就开始上来offer了，但是bootcamp我也坚持上完了，因为还是有个美国圈子更被recgonize的certificate。转码这件事呢也不能太着急，你所有学到的知识都是你的积累和收获。我个人的建议是，你可以去自己research一下你们bootcamp去年到今年的就业状况，听一听来offer的试听课，考量一下自己经济能力，自律性和职业规划然后自己去做一个判断。一但决定就努力往前走就好。加油！

**Comment by Lucie-Wang** [comment]
@linesbetween 来offer算是按照大公司的标准来要求，至于最后学生能找到什么样的工作也是要看自己的背景，努力程度，实力和运气了。我觉得这年头内推，如果不是组内的那种强链接的内推，好像都没什么用，特别是大公司。来offer有内推的服务，也有一些职位，但我个人确实没有用过，所以也不好说。我认识的大部分人都还是靠自己的努力投出来的。小一些的公司内推会比较有用。
